- name: include RHEL vars
  include_vars:
    file: "{{ ansible_distribution }}.yml"

- name: check to see if system is already registered
  command: subscription-manager status
  register: sub_status
  ignore_errors: true

- name: Register system
  redhat_subscription:
    state: present
    username: "{{ rhn_user }}"
    password: "{{ rhn_pass }}"
    # pool: "{{ rhn_pool_id }}"
    # force_register: yes
  when: sub_status.rc == 1

- name: attach to desired subscription
  command: subscription-manager attach --pool={{ rhn_pool_id }}

- name: disable all repos
  command: subscription-manager repos --disable="*"

- name: enable needed repositories
  command: subscription-manager repos --enable={{ item }}
  with_items: "{{ rhn_repos }}"

- name: install base packages
  yum:
    state: present
    name: "{{ item }}"
  with_items: "{{ base_pkgs }}"

- name: update system
  yum:
    state: latest
    name: '*'
